version: '3'

services:
  app:
    image: plos/lagotto:${CLEAN_BRANCH:-unknown}-${SHORT_HASH:-unknown}
    user: "${UID-2012}:${GID-2012}"
    build: .
    links:
      - db
      - redis
    environment:
      DATABASE_URL: mysql2://root:password@db/alm?pool=5&timeout=5000&encoding=utf8mb4
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr-mega-dev.soma.plos.org/solr/journals_dev/select
    ports:
      - 9292:9292
    volumes:
      - railsassets:/code/public
      - ./artifacts:/code/artifacts
  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
  web:
    image: nginxinc/nginx-unprivileged:1.16-alpine
    ports:
      - 8080:8080
    volumes:
      - railsassets:/code/public
      # proxy for rails app
      - ./docker/web/conf/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      - app

volumes:
  railsassets: