version: '3'

services:
  appserver:
    image: plos/lagotto:${CLEAN_BRANCH:-unknown}-${SHORT_HASH:-unknown}
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/alm?pool=5&timeout=5000&encoding=utf8mb4
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr-mega-dev.soma.plos.org/solr/journals_dev/select
      SERVERNAME: "localhost:8080"
      SUBSCRIBERS__0__JOURNAL: pmed,
      SUBSCRIBERS__0__SOURCE: crossref,
      SUBSCRIBERS__0__MILESTONES__0: 1,
      SUBSCRIBERS__0__MILESTONES__1: 15,
      SUBSCRIBERS__0__URL: http://localhost:9055/notify-me-about-xref-changes-for-journal-pmed,
    command: ["docker/start.sh", "db:3306"]
    ports:
      - 9292:9292
    volumes:
      - railsassets:/code/public
      - artifacts:/code/artifacts
  worker:
    image: plos/lagotto:${CLEAN_BRANCH:-unknown}-${SHORT_HASH:-unknown}
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql2://root:password@db/alm?pool=5&timeout=5000&encoding=utf8mb4
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr-mega-dev.soma.plos.org/solr/journals_dev/select
  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
  web:
    image: nginxinc/nginx-unprivileged:1.16-alpine
    ports:
      - 8080:8080
    volumes:
      - railsassets:/code/public
      - ./docker/web/conf/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      - appserver
  test_subscriber:
    image: nginxinc/nginx-unprivileged:1.16-alpine
    ports:
      - 9055:9055
    volumes:
      - ./docker/test-subscriber/conf/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      - appserver

volumes:
  railsassets:
  artifacts: